# serverless.yml

service: me-api-serverless

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  app:
    handler: bin/www.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'